# Generated by Django 4.2 on 2024-05-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verified_user_ver_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tg_name',
        ),
        migrations.AddField(
            model_name='user',
            name='tg_nik',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ник телеграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(blank=True, default='392273915', max_length=15, null=True, verbose_name='проверочный код'),
        ),
    ]
