# Generated by Django 4.2 on 2024-05-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_tg_name_user_tg_nik_alter_user_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(blank=True, default='297538711', max_length=15, null=True, verbose_name='проверочный код'),
        ),
    ]
